---
title: "Principal Component Analysis"
author: "Rodolfo Viana"
date: "13-10-2015"
output: html_document
---

PCA

```{r}
# source("http://factominer.free.fr/install-facto.r")

require(FactoMineR)

# The data refer to athletes’ performance during two athletics meetings.
# The data set is made of 41 rows and 13 columns: the first ten columns corresponds to
# the performance of the athletes for the 10 events of the decathlon. The columns 11 and 12
# correspond respectively to the rank and the points obtained. The last column is a categorical
# variable corresponding to the athletics meeting (2004 Olympic Game or 2004 Decastar). 
data(decathlon)

# running PCA 
# The percentage of variability explained by each dimension
res <- PCA(decathlon,
           quanti.sup=11:12, # a vector indicating the indexes of the quantitative supplementary variables
           quali.sup=13) # a vector indicating the indexes of the categorical supplementary variables


# we can describe each principal component using the dimdesc function
dimdesc(res)

plot(res,invisible="quali")

plot(res,choix="var")

plot(res,choix="var", # the graph to plot ("ind" for the individuals, "var" for the variables)   
     invisible="quanti.sup")

plot(res, 
     invisible="quali", 
     habillage=13) # color the individuals among a categorical variable (give the number of the categorical  supplementary variable or its name)

plot(res, select="contrib 7", invisible="quali") #plot the 7 individuals that have the highest cos2

plot(res,select="cos2 0.8", invisible="quali") #plot the individuals that have a cos2 greater than 0.8
plot(res,select="cos2 5", invisible="quali") #plot the 5 individuals that have the highest cos2
plot(res,choix="var",select="cos2 0.6", invisible="quali") #plot the variables that have a cos2 greater than 0.6


barplot(res$eig[,1], names.arg = paste("Dim", 1:nrow(res$eig), sep = "")) # see the importance of each dim
plot(res, choix = "var", axes = c(3, 4), lim.cos2.var = 0) # PCA with differents dim


aa <- cbind.data.frame(decathlon[,13],res$ind$coord)

bb <- coord.ellipse( # Construct confidence ellipses (ellipsoid around a point which is an estimated solution to a problem)
  aa,
  bary=TRUE) # if bary = TRUE, the coordinates of the ellipse around the barycentre of individuals are calculated

plot.PCA(res,habillage=13,ellipse=bb)
```

Correspondence analysis

```{r}
# The data used here is a contingency table that summarizes the
# answers given by different categories of people to the following question: “according to you,
# what are the reasons that can make hesitate a woman or a couple to have children?” The data
# frame is made of 18 rows and 8 columns. Rows represent the different reasons mentioned,
# columns represent the different categories (education, age) people belong to

data("children")
res.ca <- CA(children, col.sup = 6:8, row.sup = 15:18)

# Correspondence, contribution
summary(res.ca)

# plot(res.ca, invisible = c("row.sup", "col.sup"))
```

MCA

```{r}
data(tea)
summary(tea)

par(ask=T)
for (i in 1:6) barplot(table(tea[,i]))

res.mca = MCA(tea,quanti.sup=19,quali.sup=20:36)

plot(res.mca,invisible=c("var","quali.sup","quanti.sup"),cex=0.7)

plot(res.mca,invisible=c("ind","quali.sup","quanti.sup"),cex=0.8)

plot(res.mca,invisible=c("quali.sup","quanti.sup"),cex=0.8)
```

MFA

```{r}
data(wine)
res <- MFA(wine, group=c(2,5,3,10,9,2), type=c("n",rep("s",5)), 
           ncp=5, name.group=c("orig","olf","vis","olfag","gust","ens"), num.group.sup=c(1,6))

summary(res)
```